### ISSUE TITLE
No test/example project found.

### ISSUE THREAD

**Issue by shujaatak** [mkalte666/TailTipUI#1]
Can you please provide an example project using this library? or can you please guide how can I use it?

**Comment by mkalte666** [comment]
I recommend against using this library for anything productive. Instead, use something maintained and tested like [Imgui](https://github.com/ocornut/imgui)

If you absolutely must know how this works (i certainly do not remember this madness of a project well enough to tell you), in the dev-0.2 branch of this https://github.com/dreggingames/Dragon2D/tree/dev-0.2/ you can find it used. But as i said: dont. 

I keep this up as a reminder of what i coded in the past and to not loose the code, but its not good or fast or easy-to-use code. Id go as far as to say this is utter shit.
